#!/bin/bash

DIRNAME=$0
if [ "${DIRNAME:0:1}" = "/" ];then
    CURDIR=`dirname $DIRNAME`
else
    CURDIR="`pwd`"/"`dirname $DIRNAME`"
fi
echo $CURDIR

export LD_LIBRARY_PATH=$CURDIR:$LD_LIBRARY_PATH

INPUT_FILE=$1
OUTPUT_DIR="$CURDIR/techlibs/pango/outputs"
SCORE_DIR="$CURDIR/techlibs/pango/scores"

# Create a timestamp file to mark the time before synthesis
TIMESTAMP_FILE="/tmp/yosys_synth_timestamp_$$"
touch "$TIMESTAMP_FILE"

# Run synth_pango which outputs to techlibs/pango/outputs/<top_module_name>_syn.v
# The output filename is based on the top module name, not the input filename
$CURDIR/yosys -p  "synth_pango -input $INPUT_FILE"

# Find the _syn.v file that was created after the timestamp
# This ensures we get the file just generated by synth_pango, not an old one
SYN_FILE=`find $OUTPUT_DIR -name "*_syn.v" -newer "$TIMESTAMP_FILE" 2>/dev/null | head -n 1`

# Clean up timestamp file
rm -f "$TIMESTAMP_FILE"

if [ -z "$SYN_FILE" ]; then
    echo "Error: No synthesized file found in $OUTPUT_DIR/"
    echo "synth_pango may have failed or output file was not created"
    exit 1
fi

echo "Found synthesized file: $SYN_FILE"

# Extract the base name from the synthesized file for the score output
SYN_BASE_NAME=`basename $SYN_FILE _syn.v`

# Create score directory if it doesn't exist
mkdir -p "$SCORE_DIR"

# Run score command with the synthesized file from synth_pango as the -after input
$CURDIR/yosys -p  "score -before $INPUT_FILE -after $SYN_FILE -out $SCORE_DIR/${SYN_BASE_NAME}_score.txt"